name: Test Release
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test Pull Request
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install
        run: npm install
      - name: Run lint
        run: |
          npm run lint
      - name: Build
        run: |
          npm run build
      - name: Test Release
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_PHL }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --dry-run
